spring:
  application:
    name: iot-platform
  profiles:
    active: '@profile.name@'
  flyway:
    # 启动/禁用
    enabled: true
    # 迁移文件地址 flyway默认地址为 db/migration ,可根据需求自行配置
    locations: classpath:db/migration
    # 禁止清理数据库表
    clean-disabled: true
    # 如果数据库不是空表，需要设置成 true，否则启动报错
    baseline-on-migrate: true
    # 与 baseline-on-migrate: true 搭配使用,将当前数据库初始版本设置为0
    baseline-version: 0
    # 假如已经执行了版本1和版本3，如果增加了一个版本2，下面这个选项将会允许执行版本2的脚本
    out-of-order: true
    table: flyway_schema_history_${spring.application.name}